# Generated by Django 4.0.2 on 2022-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_text', models.CharField(max_length=256)),
                ('format', models.CharField(choices=[('transliteration', 'Machine Transliteration'), ('translation', 'Machine Translation'), ('both', 'Both')], max_length=15)),
            ],
        ),
    ]
