# Generated by Django 3.2.8 on 2022-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imagecaption_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='uploads/image'),
        ),
    ]
