# Generated by Django 3.2.8 on 2022-04-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imagecaption_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCaption',
            new_name='pdf_decode',
        ),
        migrations.RenameField(
            model_name='pdf_decode',
            old_name='img',
            new_name='pdf',
        ),
    ]
