# Generated by Django 3.2.8 on 2022-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220401_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_text', models.CharField(max_length=256)),
                ('format', models.CharField(choices=[('transliteration', 'Machine Transliteration'), ('translation', 'Machine Translation'), ('both', 'Both')], max_length=15)),
            ],
        ),
    ]
